name: ezformer
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
dependencies:
  - python>=3.11,<4
  - pytorch::pytorch
  - pytorch::pytorch-cuda
  - pytorch::torchvision
  - pytorch::torchaudio
  - conda-forge::torchmetrics
  - conda-forge::cuda-toolkit
  - conda-forge::wandb
  - bioconda::basenji
  - bioconda::kipoiseq
  - conda-forge::anndata
  - numpy
  - pandas
  - python-igraph
  - leidenalg
  - scikit-learn
  - matplotlib
  - dill
  - pynvml
  - ipython
  - ipykernel
  - openpyxl
  - mscorefonts
  - pip
  - pip:
    - einops
    - transformers
    - pyyaml
    - tangermeme
    - gReLU
    - modisco-lite
    - pysam
    - numba
    - lightning
    - enformer-pytorch
    - tensorflow[and-cuda]
    - tensorflow-hub
    - watermark
