name: ezformer
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
dependencies:
  - python==3.11
  - pytorch
  - pytorch-cuda==12.1
  - torchvision
  - torchaudio
  - cuda-toolkit
  - torchmetrics
  - numpy
  - pandas
  - python-igraph
  - bioconda::basenji
  - matplotlib
  - dill
  - pynvml
  - ipython
  - ipykernel
  - openpyxl
  - mscorefonts
  - pip
  - pip:
    - enformer-pytorch
    - tensorflow-gpu==2.18
    - tensorflow-hub
    - numba
    - pytdc
    - adjustText
    - watermark
    - pysam
    - einops
    - transformers
    - wandb
    - pyyaml
    - tangermeme
    - modisco-lite
