name: ezformer
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
dependencies:
  - python==3.11
  # - pytorch
  # - pytorch-cuda==12.1
  # - torchvision
  # - torchaudio
  # - torchmetrics
  - cuda-toolkit
  - numpy
  - pandas
  - python-igraph
  - leidenalg
  - scikit-learn
  - bioconda::basenji
  - matplotlib
  - dill
  - pynvml
  - ipython
  - ipykernel
  - openpyxl
  - mscorefonts
  - pip
  - pip:
    # # - enformer-pytorch
    # - tensorflow-gpu
    # - tensorflow-hub
    - numba
    - watermark
    - pysam
    - einops
    - transformers
    - wandb
    - pyyaml
    - tangermeme
    - modisco-lite
