name: ezformer
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
dependencies:
  - python==3.11
  - pytorch::pytorch
  - pytorch::pytorch-cuda
  - pytorch::torchvision
  - pytorch::torchaudio
  - conda-forge::torchmetrics
  - conda-forge::cuda-toolkit
  - bioconda::basenji
  - conda-forge::anndata
  - numpy
  - pandas
  - python-igraph
  - leidenalg
  - scikit-learn
  - matplotlib
  - dill
  - pynvml
  - ipython
  - ipykernel
  - openpyxl
  - mscorefonts
  - pip
  - pip:
    - tangermeme
    - gReLU
    - kipoiseq
    - modisco-lite
    - pysam
    - lightning
    - enformer-pytorch
    - tensorflow[and-cuda]
    - tensorflow-hub
    - numba
    - watermark
    - einops
    - transformers
    - wandb
    - pyyaml
