name: python-pkg

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      fail-fast: false
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: "Install flake8"
      run: |
        pip install flake8 tomli
    - name: "Lint with flake8"
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: "Install miniconda"
      uses: conda-incubator/setup-miniconda@v2
      with:
          miniconda-version: "latest"
          auto-update-conda: true
          mamba-version: "*"
          python-version: "3.11"
          channels: conda-forge,bioconda,pytorch,nvidia
          environment-file: environment.yml
    - name: "Install pytest"
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build pytest tomli
    - name: "Test with pytest"
      shell: bash -l {0}
      run: |
        pytest -s